// Copyright (c) Edgeless Systems GmbH.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package cli

import (
	"testing"

	"github.com/spf13/afero"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestUniqueid(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)

	fs := afero.Afero{Fs: afero.NewMemMapFs()}
	cli := NewCli(nil, fs)
	const filename = "foo"

	_, err := cli.Uniqueid(filename)
	assert.Error(err)

	require.NoError(fs.WriteFile(filename, elfUnsigned, 0))

	res, err := cli.Uniqueid(filename)
	require.NoError(err)
	assert.Equal("0000000000000000000000000000000000000000000000000000000000000000", res)
}

func TestSigneridByExecutable(t *testing.T) {
	assert := assert.New(t)
	require := require.New(t)

	fs := afero.Afero{Fs: afero.NewMemMapFs()}
	cli := NewCli(nil, fs)
	const filename = "foo"

	_, err := cli.Signerid(filename)
	assert.Error(err)

	require.NoError(fs.WriteFile(filename, elfUnsigned, 0))

	res, err := cli.Signerid(filename)
	require.NoError(err)
	assert.Equal("0000000000000000000000000000000000000000000000000000000000000000", res)
}

func TestSigneridByKey(t *testing.T) {
	// generated by `openssl genrsa -3 3072 | openssl rsa -pubout`
	const pubkey = `-----BEGIN PUBLIC KEY-----
MIIBoDANBgkqhkiG9w0BAQEFAAOCAY0AMIIBiAKCAYEA0+9/xzM9twAG6CuQf7LM
5Lx88UG5+y7dNqGT6RtduNi0FMBEUzlKfMkXTXDusl5c3SQKN7HXLr93W9SQ3+5m
60r+PkmylgYG+U3n2xyt0WZ+tQOigyfwQIPukxLQVMlqCu+BdxxnDjay+Xq23U+g
QsMXCfgsZtOCDnqA7yUEueRcPmrmtbQOqjtE3b6YMp0sPCYZ+zGfKUUEirUOEiD3
TdUGTjLvx0Wc+swLewhM5NLxX9zNVAGqFG23SAkvMfGXC975FQc9PwZhAkD2RqHm
UL4mcut6z8c2TEstde7jKUziiUv6nVGjQ+RsIk8gbpvGIgg2U1WHyy1pjvD61mBk
Stm3+7uzQnWtj0NjLfdvJvLj/R3idafzb0RfgNUbNlfMTg0Sx/yt5W4cu1d/5evx
CQZ6NKedMmT53RSwRk2PNKE4rzR7uED2k7SVW226/jgpeV6myL9Qp5yZq2hkQojV
fEt/+v8tVFz7f/SRw1Ps7yUzM7cuZaXEE+jQDuAp22ThAgED
-----END PUBLIC KEY-----`
	const expected = "af03bba19883bea794bb72d0213d6088a828af3f7f056c2b24808e1677766e50"

	assert := assert.New(t)
	require := require.New(t)

	fs := afero.Afero{Fs: afero.NewMemMapFs()}
	cli := NewCli(nil, fs)
	const filename = "foo.pem"

	_, err := cli.Signerid(filename)
	assert.Error(err)

	require.NoError(fs.WriteFile(filename, []byte(pubkey), 0))

	res, err := cli.Signerid(filename)
	require.NoError(err)
	assert.Equal(expected, res)
}
