FROM ubuntu:focal-20230624
RUN apt-get update && apt-get install -dy --no-install-recommends \
  build-essential \
  ca-certificates \
  clang-11 \
  cmake \
  git \
  libssl-dev \
  ninja-build \
  wget
