// Code generated by "stringer -type=Status"; DO NOT EDIT.

package tcbstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpToDate-0]
	_ = x[OutOfDate-1]
	_ = x[Revoked-2]
	_ = x[ConfigurationNeeded-3]
	_ = x[OutOfDateConfigurationNeeded-4]
	_ = x[SWHardeningNeeded-5]
	_ = x[ConfigurationAndSWHardeningNeeded-6]
	_ = x[Unknown-7]
}

const _Status_name = "UpToDateOutOfDateRevokedConfigurationNeededOutOfDateConfigurationNeededSWHardeningNeededConfigurationAndSWHardeningNeededUnknown"

var _Status_index = [...]uint8{0, 8, 17, 24, 43, 71, 88, 121, 128}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
