name: ego-dev
base: core20
version: "1.4.1"
summary: EGo lets you build, debug und run Go apps on Intel SGX!
description: EGo is a framework for building confidential apps in Go. Confidential apps run in always-encrypted and verifiable enclaves on Intel SGX-enabled hardware.

grade: stable
confinement: classic

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  ego:
    command: opt/ego/bin/ego
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    completer: etc/bash_completion.d/ego_completion
  ego-go:
    command: opt/ego/bin/ego-go
  ego-gdb:
    command: opt/ego/bin/ego-gdb
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

parts:
  ego:
    source: https://github.com/edgelesssys/ego/releases/download/v1.4.1/ego_1.4.1_amd64_ubuntu-20.04.deb
    source-checksum: "sha256/e71045e2a08e3b191625e9f89cfe4135e2f99aa5b25d982f71bf2a2434c0f6c9"
    source-type: deb
    plugin: dump
    build-attributes: [no-patchelf] # needed otherwise Snap breaks the go binary, causing it to segfault on launch
    # fix symlinks in .deb release package, they point outside of the snap environment and snapcraft will automatically add them anyway
    override-build: |
      rm -f $SNAPCRAFT_PART_BUILD/usr/local/bin/ego-go
      rm -f $SNAPCRAFT_PART_BUILD/usr/local/bin/ego-gdb
      rm -f $SNAPCRAFT_PART_BUILD/usr/local/bin/ego
      sed -i 's/-F __start_ego ego/-F __start_ego ego-dev.ego/' $SNAPCRAFT_PART_BUILD/etc/bash_completion.d/ego_completion
      snapcraftctl build
    stage-packages: [libsgx-enclave-common, libsgx-dcap-ql, libssl1.1]

package-repositories:
  - type: apt
    components: [main]
    suites: [focal]
    key-id: 150434D1488BF80308B69398E5C7F0FA1C6C6C3C
    url: https://download.01.org/intel-sgx/sgx_repo/ubuntu
