name: Links

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - "**.html"
      - ".github/workflows/links.yml"
  pull_request:
    paths:
      - "**.md"
      - "**.html"
      - ".github/workflows/links.yml"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.1
        with:
          fail: true
