name: Links

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - "**.html"
  pull_request:
    paths:
      - "**.md"
      - "**.html"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
