name: Vale
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: errata-ai/vale-action@reviewdog
        with:
          files: docs/docs
          fail_on_error: true
          version: 3.9.3
